- name: install PBIS-open
  shell: yes | /vagrant/files/install/pbis-open-8.5.2.265.linux.x86_64.rpm.sh

- name: set /etc/resolv.conf file to AD address
  template:
    src: resolv.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root

- name: add FQDN to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ ansible_all_ipv4_addresses[0] }} {{ ansible_hostname }}.{{ groupvar_ad_domain }} {{ ansible_hostname }}"
    insertafter: EOF
    mode: 0644

- name: add local machine to AD
  shell: 'echo {{ groupvar_ad_rootuser_password }} | /opt/pbis/bin/domainjoin-cli join {{ groupvar_ad_domain }} {{ groupvar_ad_rootuser }}'
  no_log: false

- name: set PBIS-open paramaters
  shell: "{{ item }}"
  no_log: true
  with_items:
    - '/opt/pbis/bin/domainjoin-cli configure --enable ssh'
    - '/opt/pbis/bin/config HomeDirTemplate "%H/%D/%U"'
    - '/opt/pbis/bin/config Local_HomeDirTemplate "%H/%D/%U"'
    - '/opt/pbis/bin/config LoginShellTemplate "/bin/bash"'
    - '/opt/pbis/bin/config UserDomainPrefix "{{ groupvar_ad_domain_prefix }}"'
    - '/opt/pbis/bin/config AssumeDefaultDomain true'
    - '/opt/pbis/bin/config NssEnumerationEnabled False'
    - '/opt/pbis/bin/config HomeDirUmask "0777"'