ansible_user: vagrant
ansible_password: vagrant
ansible_ssh_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

gradle_archive: 'C:\{{ gradle_package }}'
gradle_install: 'C:\Program Files\gradle'
gradle_home: '{{ gradle_install }}\gradle-{{ gradle_version }}'
gradle_bin: '{{ gradle_home }}\bin'
gradle_bin_regex: ';?C:\\Program Files\\gradle\\gradle-3\.3\\bin'
