---
# handlers file for pbis
  - name: config pbis ssh
    command: /opt/pbis/bin/domainjoin-cli configure --enable ssh

  - name: config pbis homedirtemplate
    command: /opt/pbis/bin/config HomeDirTemplate {{ homedir_template }}

  - name: config pbis localhomedirtemplate
    command: /opt/pbis/bin/config Local_HomeDirTemplate {{ local_homedir_template }}

  - name: config pbis shell
    command: /opt/pbis/bin/config LoginShellTemplate {{ login_shell_template }}

  - name: config pbis userdomainprefix
    command: /opt/pbis/bin/config UserDomainPrefix {{ groupvar_ad_domain_prefix }}

  - name: config pbis assumedefaultdomain
    command: /opt/pbis/bin/config AssumeDefaultDomain {{ assume_default_domain }}

  - name: config pbis nssenumeration
    command: /opt/pbis/bin/config NssEnumerationEnabled {{ nss_enumeration_enabled }}

  - name: config pbis homedirumask
    command: /opt/pbis/bin/config HomeDirUmask {{ home_dir_umask }}

#   - name: add FQDN to hosts file
#     lineinfile:
#       dest: /etc/hosts
#       state: present
#       line: "{{ ansible_all_ipv4_addresses[0] }} {{ ansible_hostname }}.{{ groupvar_ad_domain }} {{ ansible_hostname }}"
#       insertafter: EOF
#       mode: 0644
#
#
#   - name: add AD servers to resolv.conf
#     lineinfile:
#       dest: /etc/resolv.conf
#       state: present
#       line: "{{ item }}"
#       mode: 0644
#     with_items:
#       - 'nameserver 192.168.80.13'
#       - 'search {{ groupvar_ad_domain }}'