- name: get contents (shell)
  shell: cat /tmp/group_* | tr -d "\n" | tr "\"" "\'"
  register: output
  delegate_to: 127.0.0.1
  notify:
    - get contents (set fact)

- name: get contents (set fact)
  set_fact:
    contents: "{{output.stdout}}"
  delegate_to: 127.0.0.1
  changed_when: true
  notify:
    - add pagelist to confluence ( PUT )

- name: add pagelist to confluence ( PUT )
  uri:
    url: "{{ confluence_url }}/{{ list.json.results[0].id }}"
    HEADER_Content-Type: "application/json"
    method: PUT
    body : "{{ lookup('template','/etc/ansible/roles/all-confluence-refresh/templates/updatepage_list.j2') }}"
    body_format: json
    user: "{{ confluence_user }}"
    password: "{{ confluence_pass }}"
    return_content: yes
    force_basic_auth: yes
  changed_when: true
  run_once: true
  delegate_to: 127.0.0.1
  notify:
    - delete tmp file

- name: delete tmp file
  delegate_to: 127.0.0.1
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /tmp/group_*

